# Generated by Django 4.2.29 on 2026-04-09 11:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name_plural': 'Usuarios Lili',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('openlibrary_key', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('publica', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('formato', models.CharField(blank=True, choices=[('t_dura', 'Tapa dura'), ('t_blanda', 'Tapa blanda'), ('bolsillo', 'Bolsillo')], max_length=10, null=True)),
                ('ano_pub', models.DateField(blank=True, null=True)),
                ('ano_pub_og', models.DateField(blank=True, null=True)),
                ('portada', models.CharField(blank=True, max_length=200, null=True)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('openlibrary_key', models.CharField(blank=True, max_length=16, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('autores', models.ManyToManyField(related_name='libros', to='lili_api.autor')),
            ],
            options={
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='LibroCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lili_api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('volumenes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='UsuarioLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_en_serie', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('leido', 'Leído'), ('leyendo', 'Leyendo'), ('ab', 'Abandonado'), ('s_e', 'Sin empezar')], default='s_e', max_length=10, null=True)),
                ('favorito', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('fecha_anadido', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(related_name='libros_usuario', through='lili_api.LibroCategoria', to='lili_api.categoria')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='lili_api.libro')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lili_api.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('solicitado', 'Solicitado')], default='activo', max_length=16)),
                ('prestatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lili_api.usuariolibro')),
            ],
            options={
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=42)),
                ('texto', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('referencia', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.AddField(
            model_name='librocategoria',
            name='usuario_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lili_api.usuariolibro'),
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('s_s', 'Sin solicitar'), ('pen', 'Pendiente'), ('ac', 'Aceptada'), ('blo', 'Bloqueada')], default='s_s', max_length=16)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('usuario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_enviadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Amistades',
            },
        ),
        migrations.AddField(
            model_name='usuariolili',
            name='libros',
            field=models.ManyToManyField(related_name='usuarios', through='lili_api.UsuarioLibro', to='lili_api.libro'),
        ),
        migrations.AddField(
            model_name='usuariolili',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='usuariolibro',
            constraint=models.UniqueConstraint(fields=('usuario', 'libro'), name='libros_no_duplicados'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('usuario_libro',), name='unique_prestamo_activo'),
        ),
        migrations.AlterUniqueTogether(
            name='librocategoria',
            unique_together={('usuario_libro', 'categoria')},
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='categorias_no_duplicadas'),
        ),
        migrations.AddConstraint(
            model_name='amistad',
            constraint=models.UniqueConstraint(fields=('usuario_a', 'usuario_b'), name='unique_amistad'),
        ),
        migrations.AddConstraint(
            model_name='amistad',
            constraint=models.CheckConstraint(check=models.Q(('usuario_a', models.F('usuario_b')), _negated=True), name='no_autoamistad'),
        ),
    ]
