# Generated by Django 4.2.29 on 2026-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lili_api', '0002_editorial_libro_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
