# Generated by Django 4.2.30 on 2026-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lili_api', '0003_alter_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
